import './globals.css'
import { Inter } from 'next/font/google'
import dynamic from 'next/dynamic'
import { Suspense } from 'react'

const inter = Inter({ subsets: ['latin'] })

const Chatbot = dynamic(
  () => import('./components/Chatbot').then((c) => c.default),
  { 
    ssr: false,
    loading: () => (
      <div className="fixed bottom-4 right-4 w-12 h-12 bg-blue-500 rounded-full flex items-center justify-center">
        <div className="animate-pulse text-white">...</div>
      </div>
    )
  }
)

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Suspense fallback={null}>
          <Chatbot />
        </Suspense>
      </body>
    </html>
  )
}